export const JOB = {
  PROCESS_INBOUND_WHATSAPP_MESSAGE: "PROCESS_INBOUND_WHATSAPP_MESSAGE",
  GENERATE_AI_RESPONSE: "GENERATE_AI_RESPONSE",
  SEND_WHATSAPP_MESSAGE: "SEND_WHATSAPP_MESSAGE",
  PROCESS_POST_SALE_TICK: "PROCESS_POST_SALE_TICK",
} as const;

export type JobName = (typeof JOB)[keyof typeof JOB];
